# config/config.yml
---
paths:
  qc_report_path: "/path/to/qc_report.csv"
  roi_signals_dir: "/path/to/roi_signals"
  output_dir: "/path/to/output"

atlas:
  aal3_meta_path: "/path/to/aal3_meta.tsv"
  aal3_missing_indices_1based: [1, 2, 3]  # Ejemplo: Índices faltantes
  small_roi_voxel_threshold: 10  # Ejemplo: Umbral para ROIs pequeños

preprocessing:
  tr_seconds: 2.0  # Tiempo de repetición en segundos
  low_cut_hz: 0.01  # Frecuencia de corte inferior para el filtro pasa banda
  high_cut_hz: 0.1  # Frecuencia de corte superior para el filtro pasa banda
  filter_order: 5  # Orden del filtro de Butterworth
  target_length_tps: 200  # Longitud objetivo de puntos temporales

features:
  # Configuración para extracción de características
  connectivity:
    methods: ["pearson", "partial_correlation"]
  complexity:
    methods: ["sample_entropy", "permutation_entropy"]
