# --- Rutas (asegúrate de que sean correctas) ---
paths:
  qc_output_dir: './qc_outputs_refactored_v1.0'
  qc_report_filename: 'report_qc_final.csv'
  base_output_dir: './connectivity_features'
  roi_signals_dir: '/home/diego/Escritorio/AAL3/ROISignals_AAL3_NiftiPreprocessedAllBatchesNorm'
  atlas_nifti_path: '/home/diego/Escritorio/AAL3/AAL3v1.nii.gz'

# --- Atlas y ROIs ---
atlas:
  aal3_meta_path: '/home/diego/Escritorio/AAL3/ROI_MNI_V7_vol.txt'
  aal3_missing_indices_1based: [35, 36, 81, 82]
  small_roi_voxel_threshold: 100

# --- Preprocesamiento de Series Temporales ---
preprocessing:
  tr_seconds: 3.0
  low_cut_hz: 0.01  # Umbral seguro para evitar errores en wavelet
  high_cut_hz: 0.08
  filter_order: 2
  target_length_tps: 140

# --- Selección de Canales (Ahora con más opciones) ---
channels:
  # Base
  pearson_full: true
  graphical_lasso: true
  # Dinámica
  sliding_std_corr: true
  # No Lineal
  distance_corr_full: true
  mutual_info_full: true # Lento, activar con cautela
  # Dirigida
  granger_pairwise: true   # Muy lento, activar con cautela
  # Frecuencia
  wavelet_coh_slow: false
  wavelet_coh_fast: false
  # Opcionales del pipeline anterior
  pearson_omst: true
  tangent_space: true

# --- Características Adicionales (sin cambios) ---
features:
  hmm_dynamics: true
  graph_topology: true

# --- Parámetros Específicos ---
parameters:
  hmm:
    n_states: 5
    n_iter: 150
    covariance_type: 'diag'
  
  graphical_lasso:
    cv_folds: 3

  wavelet:
    num_freqs_per_band: 10 # Menos freqs por banda para acelerar
    cwt_n_cycles: 4

  # --- Nuevos parámetros ---
  mutual_info:
    n_bins: 8 # Número de bins para discretizar la señal

  granger:
    max_lag: 1 # Lag para la causalidad de Granger

  sliding_window:
    win_len: 30 # 30 TRs = 90 segundos
    step: 5     # Paso de 5 TRs

# --- Paralelización ---
max_workers: 4