# --- Rutas (asegúrate de que sean correctas) ---
paths:
  qc_output_dir: './qc_outputs_refactored_v1.0'
  qc_report_filename: 'report_qc_final.csv'
  base_output_dir: './connectivity_features'
  roi_signals_dir: '/home/diego/Escritorio/AAL3/ROISignals_AAL3_NiftiPreprocessedAllBatchesNorm'
  atlas_nifti_path: '/home/diego/Escritorio/AAL3/AAL3v1.nii.gz'

# --- Atlas y ROIs ---
atlas:
  aal3_meta_path: '/home/diego/Escritorio/AAL3/ROI_MNI_V7_vol.txt'
  aal3_missing_indices_1based: [35, 36, 81, 82]
  small_roi_voxel_threshold: 100

# --- Preprocesamiento de Series Temporales ---
preprocessing:
  tr_seconds: 3.0
  low_cut_hz: 0.01  # Umbral seguro para evitar errores en wavelet
  high_cut_hz: 0.08
  filter_order: 2
  target_length_tps: 140

# --- Selección de Canales (TODOS ACTIVOS) ---
channels:
  pearson_full: true
  pearson_omst: true
  graphical_lasso: true
  tangent_space: true
  wavelet_coherence: false # Activado gracias a las correcciones

# --- Características Adicionales ---
features:
  hmm_dynamics: true
  graph_topology: true

# --- Parámetros Específicos ---
parameters:
  hmm:
    n_states: 5
    n_iter: 150
    covariance_type: 'diag'
  
  graphical_lasso:
    cv_folds: 3 # Reducido para aligerar el cómputo

  wavelet:
    num_freqs: 15 # Reducido para aligerar el cómputo
    cwt_n_cycles: 3 # El ajuste clave para que funcione con señales cortas

# --- Paralelización (CONTROL DE RECURSOS) ---
max_workers: 4 # Un valor seguro y razonablemente rápido para tu máquina