# Archivo de Configuración: Experimento Tesis v5.0 (Arquitectura Modular)
# --------------------------------------------------------------------
# Descripción: Ejecución con arquitectura de VAE configurable, incluyendo
#              capas convolucionales y lineales definidas por el usuario.

# --- Rutas y Selección de Datos ---
run_dir: './connectivity_features/connectivity_8ch_20250611_154317'
output_dir: './results/exp_modular_v5'
# Canales seleccionados según el ranking de información mutua.
# Puedes ajustar esto basado en tus análisis.
channels_to_use: [0, 2, 3, 4, 5, 7]

# --- Arquitectura del VAE (NUEVA SECCIÓN MODULAR) ---
latent_dim: 512
num_conv_layers: 4
decoder_type: 'convtranspose' # 'convtranspose' o 'upsample_conv'
# Canales de salida para cada capa convolucional del encoder
vae_conv_channels: [32, 64, 128, 256]
# Tamaños de kernel para cada capa convolucional del encoder
vae_kernel_sizes: [7, 5, 5, 3]
# Paddings para cada capa
vae_paddings: [1, 1, 1, 1]
# Strides para cada capa
vae_strides: [2, 2, 2, 2]
# Dimensión de la capa lineal intermedia (0 para no usarla)
intermediate_fc_dim: 2048
# Usar LayerNorm en las capas lineales (muy recomendado)
use_layernorm_fc: true
# Función de activación final del decoder
final_activation: 'tanh'

# --- Parámetros de Entrenamiento ---
beta: 1.5
dropout_rate: 0.2
epochs: 550
lr: 0.0001
batch_size: 32
weight_decay: 0.00001
optimizer: 'adamw'
scheduler: 'cosine'
lr_warmup_epochs: 100
beta_cycles: 3
kl_start_epoch: 15
early_stopping: 55
clip_grad_norm: 1.0

# --- Validación Cruzada y Clasificador ---
n_folds: 5
# Ahora con más opciones de clasificadores
classifier_types: ['rf', 'svm', 'logreg', 'gb', 'mlp']
stratify_on: ['ResearchGroup', 'Sex']

# --- General ---
seed: 42