# Archivo de Configuración: Replicando el experimento de 'wed_night.py'
# --------------------------------------------------------------------
# Descripción: Esta configuración busca replicar los resultados de la ejecución anterior
#              ajustando los parámetros a los utilizados en el script v1.5.1.

# --- Rutas y Selección de Datos ---
# ATENCIÓN: Debes reemplazar 'run_dir' con la ruta correcta a los datos pre-procesados
# por 'prepare_and_analyze_data.py' en tu nuevo pipeline.
run_dir: './connectivity_features/connectivity_8ch_20250611_154317' 
output_dir: './results/REPLICA_wed_night'
channels_to_use: [0, 2, 3, 7] # Equivalente a --channels_to_use 1 2 3

# --- Arquitectura del VAE (Modular) ---
# Coincide con los parámetros de la ejecución anterior
latent_dim: 512
num_conv_layers: 4
decoder_type: 'convtranspose'
# La arquitectura de canales convolucionales, kernels, etc., está ahora
# codificada en el modelo, pero estos parámetros la controlan.
vae_conv_channels: [32, 64, 128, 256] 
vae_kernel_sizes: [7, 5, 5, 3]
vae_paddings: [1, 1, 1, 1]
vae_strides: [2, 2, 2, 2]
intermediate_fc_dim: 1024
use_layernorm_fc: true
final_activation: 'tanh'

# --- Parámetros de Entrenamiento ---
# Coincide con los parámetros de la ejecución anterior
beta: 1.0 # Equivalente a --beta_vae
dropout_rate: 0.2
epochs: 550
lr: 0.0001 # Equivalente a --lr_vae
batch_size: 64
weight_decay: 0.00001 # Equivalente a --weight_decay_vae
optimizer: 'adamw' # El nuevo script usa AdamW por defecto, puedes cambiarlo si es necesario
scheduler: 'cosine' # El nuevo script usa Coseno, el anterior usaba ReduceLROnPlateau
lr_warmup_epochs: 50 # Puedes ajustar este valor si lo deseas
beta_cycles: 2 # Equivalente a --cyclical_beta_n_cycles
kl_start_epoch: 0 # El equivalente más cercano al schedule anterior
early_stopping: 50
clip_grad_norm: 1.0 # Un valor por defecto robusto

# --- Validación Cruzada y Clasificador ---
n_folds: 5
# El nuevo script soporta 'lgbm', pero mantenemos los originales para replicar
classifier_types: ['rf', 'gb', 'svm', 'logreg', 'mlp'] 
stratify_on: ['ResearchGroup', 'Sex']

# --- General ---
seed: 42